version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"
    groups:
      all-minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/extensions/chrome"
    schedule:
      interval: "monthly"
    groups:
      all-minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
