name: API test

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: api
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install NodeJS 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
