name: Chrome extension test

on:
  pull_request:
    branches:
      - main
    paths:
      - "extensions/chrome-vite-react/**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: extensions/chrome-vite-react
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
